### PR TITLE
feat(file_info): add read-only indicator

### LINKED ISSUE #35: Read only tag on the feline would be great
some times we start editing a file then if we try to save it it shows read only can you add  a read only tag in feline that would be great

### PR DESCRIPTION
**Pull request by famiu**
Closes #35

### CODE REVIEW

**Comment by famiu** [comment]
Wondering if the indicator should be a part of file_info as it is now in the PR or if I should modularize it into a separate component

**Comment by ram02z** [comment]
>
> Wondering if the indicator should be a part of file_info as it is now in the PR or if I should modularize it into a separate component

I think you should make it a separate component as it will allow users to set custom highlighting for the provider.

**Comment by famiu** [comment]
> > Wondering if the indicator should be a part of file_info as it is now in the PR or if I should modularize it into a separate component
> 
> I think you should make it a separate component as it will allow users to set custom highlighting for the provider.

While that's a valid point, the modified indicator is also a part of file_info and that doesn't seem to cause any issues. Making a separate component, while allowing higher customizability, will increase component clutter. So I'm not sure if the tradeoff is worth it

**Comment by famiu** [comment]
After giving it some thought I'm going to go with putting it in file_info, it's just way simpler imo and I believe that showing whether the file is read-only or not is within the scope of the file_info provider.

**Pull request merged**
