### PR TITLE
fix: make statusline update in all windows

### LINKED ISSUE #52: [Bug] statusline is updated only in current window
**Neovim version**
NVIM v0.5.0
Build type: Release
LuaJIT 2.0.5

**Feline version**
8c809b2416fa6773719f3c391eb7b124d67c866e (latest as of now)

**Describe the bug**
Statusline is updated only in current window, so inactive statusline isn't updated. This is a problem because in the inactive part i put the window number (return value of `vim.fn.winnr()`) to make easier to jump between windows with a keybinding (space+number). When deleting a window, for example, window numbers aren't updated, making navigation between windows difficult.

**To Reproduce**
1. Vertical split (`<C-w>v`)
2. Vertical split (`<C-w>v`)
3. Go to first window (`<C-w>w`)
4. Delete it (`<C-w>c`)
5. The window on the right shows number 3, even if it is window 2.

If you jump to window 2 and come back to window 1 you'll see the number updated.

**Expected behavior**
Inactive windows should be updated.

**Screenshots**
After step 3:
st1

After step 4:
st2

### PR DESCRIPTION
**Pull request by famiu**
Closes #52

I'd like people to review it and check if everything works as intended before I merge this.

### CODE REVIEW

**Comment by ram02z** [comment]
If you start telescope (in insert mode) and open a file, the windows statusline doesn't get updated and the vi provider is stuck on insert mode. I can also reproduce with nnn.vim, following the same steps, but instead the vi provider is stuck on terminal mode. Also, floating windows trigger an inactive and empty statusline, not sure if thats intended. 

Strange behaviour when you have a split open with files of different filetypes, I think this shows that the wrong window is getting updated.

Reproduction steps:
1. Open two files of two different filetypes
2. Create a split to force one window to have an inactive statusline
3. The unfocused window will show the filetype of the focused file (this is using the default config).

**Comment by xeluxee** [comment]
It looks like feline is updated in every window but with active window data.

st1
As you can see in the image, if I go to NvimTree every window shows NvimTree and window number 1

In the same way if I go on split 2 every window gets its infos from the second window
st2

**Comment by famiu** [comment]
@xeluxee @ram02z So I'm trying to edit the providers so they can take the window number and use the appropriate buffer to show their info. But an issue I came across while doing that is related to the Git provider. Git uses the gitsigns_status_dict of gitsigns.nvim, which it only seems to provide for the current buffer. So it wouldn't be possible to use it for inactive windows, unless there's a way. Thoughts?

**Comment by ram02z** [comment]
I was playing around the code, and I think the only way to ensure that the win number is correct is to make it a named argument for function providers.

**Comment by famiu** [comment]
> I was playing around the code, and I think the only way to ensure that the win number is correct is to make it a named argument for function providers.

That is what I'm doing. And I'm actually just done with that. Will make a separate PR for it in a bit, just need to do some final cleanups

**Comment by xeluxee** [comment]
Give a look at [`nvim_win_call`](https://neovim.io/doc/user/api.html#nvim_win_call())
It lets you execute a function as it was in a specific window.

**Comment by famiu** [comment]
@ram02z @xeluxee Okay so I'm done with stuff. But there's one issue, I need to use the gitsigns_status_dict and gitsigns_head buffer values of gitsigns.nvim for the git providers. In order to do that, I used `vim.api.nvim_buf_get_var`. But the problem with that is, gitsigns doesn't immediately define the dicts after startup, and if the dict doesn't exist, `vim.api.nvim_buf_get_var` shows an error, whereas previously I used `vim.b.gitsigns_status_dict` directly which just returned nil if it wasn't defined, which was easy to check. Any ideas on how to work around that?

**Comment by ram02z** [comment]
You could wrap it in a pcall, kind of like this:
```lua
local ok, value = pcall(vim.api.nvim_buf_get_var, 0, "...")
if not ok then
  return
end
```

**Comment by famiu** [comment]
> You could wrap it in a pcall, kind of like this:
> 
> ```lua
> local ok, value = pcall(vim.api.nvim_buf_get_var, 0, "...")
> if not ok then
>   return
> end
> ```

Tried that already, doesn't work

**Comment by ram02z** [comment]
`vim.fn.getbufvar` returns an empty string when the variable is not found.

**Comment by famiu** [comment]
> You could wrap it in a pcall, kind of like this:
> 
> ```lua
> local ok, value = pcall(vim.api.nvim_buf_get_var, 0, "...")
> if not ok then
>   return
> end
> ```

That's what I tried at first, but it didn't work. Then after seeing your code I realized I made a silly mistake which was causing it to not work, but it works now!

**Comment by famiu** [comment]
Merging #56 would be needed before I can make further progress on this, so it'd be nice if that was tested out.

**Comment by xeluxee** [comment]
@famiu just wondering why not using [`nvim_win_call`](https://neovim.io/doc/user/api.html#nvim_win_call())
It would be simpler, there wouldn't be any need to edit current providers...

**Comment by famiu** [comment]
> @famiu just wondering why not using [`nvim_win_call`](https://neovim.io/doc/user/api.html#nvim_win_call())
> It would be simpler, there wouldn't be any need to edit current providers...

well, let me see if I can do that, then

**Comment by famiu** [comment]
> @famiu just wondering why not using [`nvim_win_call`](https://neovim.io/doc/user/api.html#nvim_win_call())
> It would be simpler, there wouldn't be any need to edit current providers...

How would we use it to call providers that take an argument? As far as I can see, it only works for functions that don't take any arguments

**Comment by famiu** [comment]
I incorporated the changes in #56 in this PR and closed #56 since it's not usable by itself and needs the changes in this PR to function properly.

**Comment by famiu** [comment]
First problem I noticed: the cursor doesn't update and I don't have any idea why. Need to look into it more

**Comment by famiu** [comment]
> First problem I noticed: the scroll indicator doesn't update and I don't have any idea why. Need to look into it more

It seems that it's not unique to the scroll indicator, none of the providers except the file position are updated, probably because the file position provider uses Neovim's built-in statusline component variables. This indicates that the generator is only being called once when the buffer is opened.

**Comment by famiu** [comment]
I managed to fix the components not being updated

**Comment by famiu** [comment]
It seems some components (such as the git branch name) are still not being updated, need to look into it more

**Comment by xeluxee** [comment]
> > @famiu just wondering why not using [`nvim_win_call`](https://neovim.io/doc/user/api.html#nvim_win_call())
> > It would be simpler, there wouldn't be any need to edit current providers...
> 
> How would we use it to call providers that take an argument? As far as I can see, it only works for functions that don't take any arguments

@famiu this is a sample code using [`nvim_win_call`](https://neovim.io/doc/user/api.html#nvim_win_call())
``` lua
local myfunc = function (add, sub)
  print(string.format("Window number %d has id %d: value %d", vim.fn.winnr(), vim.fn.win_getid(), vim.fn.winnr()+add-sub))
end

for winnr, winid in pairs(vim.api.nvim_list_wins()) do
  vim.api.nvim_win_call(winid, function() myfunc(5, -5) end)
end
```

Output:
```
Window number 1 has id 1008: value 11                                                                                                                                         
Window number 2 has id 1000: value 12 
```

**Comment by xeluxee** [comment]
> I managed to fix the components not being updated. This seems to be ready for merge now. Just need people to review it

I'm using 4727b3535a43832d088e70f525a17704beb159eb and this problem remains: every window takes data from current window
st1

**Comment by famiu** [comment]
> > I managed to fix the components not being updated. This seems to be ready for merge now. Just need people to review it
> 
> I'm using [4727b35](https://github.com/famiu/feline.nvim/commit/4727b3535a43832d088e70f525a17704beb159eb) and this problem remains: every window takes data from current window
> st1

Cannot reproduce the issue. Does this work for you @ram02z?

**Comment by ram02z** [comment]
> 
> Cannot reproduce the issue. Does this work for you @ram02z?

I can reproduce if I use a provider that returns `vim.fn.winnr()`. However, it updates fine when I use the `winnr` parameter. However, the `winnr` parameter actually returns the window handle, not number, which I guess won't solve @xeluxee 's issue. 
`nvim_list_wins` returns a table of window handles.

**Comment by famiu** [comment]
> I can reproduce if I use a provider that returns `vim.fn.winnr()`. However, it updates fine when I use the `winnr` parameter.
> However, the `winnr` parameter actually returns the window handle, not number, which I guess won't solve @xeluxee 's issue.

Just use `nvim_win_get_number`

**Comment by ram02z** [comment]
Ok since we have decided to take the reliable approach, I would also like to see a few of the changes made in #58 be introduced to this PR.

1. Update only inactive windows. There is no reason to update the active window because we reset the local statusline of the current window to use the global statusline for it anyway.
2. Filter out windows that we don't care about like floating windows and the current window.
3. Iterate over the tabpage windows not all the windows, since not all the windows are visible.
3. This is probably the most important change and it is to reduce the amount of autocmds we use to trigger the update of inactive windows. The reason I say this is that firstly we should avoid unnecessary redraws when possible. These unnecessary redraws can cause unforeseen issues like the one with we noticed with lsp hover. The culprit autocmd was `BufEnter` and by introducing it, we are also introducing a regression that was fixed upstream https://github.com/neovim/neovim/pull/10112. I have already found the bare minimum autocmds; VimEnter, WinEnter, FileChangedShellPost.

Another change unrelated to #58 is quite simple, change references of `winnr` to `winid` because we aren't actually providing the window number. 

Here is the patch I am using currently that builds on this PR based on my above comments: https://gist.github.com/ram02z/59761a0acb7fb86bccf71f84bc0c955d

**Comment by famiu** [comment]
> Ok since we have decided to take the reliable approach, I would also like to see a few of the changes made in #58 be introduced to this PR.
> 
>     1. Update only inactive windows. There is no reason to update the active window because we reset the local statusline of the current window to use the global statusline for it anyway.
> 
>     2. Filter out windows that we don't care about like floating windows and the current window.
> 
>     3. Iterate over the tabpage windows not all the windows, since not all the windows are visible.
> 
>     4. This is probably the most important change and it is to reduce the amount of autocmds we use to trigger the update of inactive windows. The reason I say this is that firstly we should avoid unnecessary redraws when possible. These unnecessary redraws can cause unforeseen issues like the one with we noticed with lsp hover. The culprit autocmd was `BufEnter` and by introducing it, we are also introducing a regression that was fixed upstream [api/buffer: avoid spurios Buf[Win]Enter in nvim_buf_set_lines neovim/neovim#10112](https://github.com/neovim/neovim/pull/10112). I have already found the bare minimum autocmds; VimEnter, WinEnter, FileChangedShellPost. Working our way up is more reliable in my opinion.
> 
> 
> Another change unrelated to #58 is quite simple, change references of `winnr` to `winid` because we aren't actually providing the window number.
> 

I had actually already made all of the changes you listed before, just didn't push them yet. I've pushed them now

**Comment by famiu** [comment]
Also I've tested this for a while, it seems to work fine for me. I didn't notice any slowdowns either so for all intents and purposes the performance seems to be about the same, which should be the case since inactive windows are updated only when the autocmd triggers. I'm wondering whether to merge this or wait for further testing

**Comment by ram02z** [comment]
I think the only side effects this PR may have is that the someone may find a scenario whereby the inactive statusline isn't updating, but I haven't noticed any issues either, so if a scenario does arise, it will most likely be solved by adding the appropriate autocmd.

**Comment by famiu** [comment]
> I think the only side effects this PR may have is that the someone may find a scenario whereby the inactive statusline isn't updating, but I haven't noticed any issues either, so if a scenario does arise, it will most likely be solved by adding the appropriate autocmd.

With that considered, I'm going to merge this then

**Comment by xeluxee** [comment]
I can confirm this PR works well:
- providers in inactive windows works well thanks to `winid` parameter
- LSP hover doesn't make feline inactive in current window

But NvimTree problem remains, and it's independent from `splitright` because in another scenario inactive windows aren't updated.
To reproduce (no matter of `splitright` value):
1. Open a buffer fullscreen
2. Split vertically
3. Launch `:NvimTreeToggle`
4. Go to middle window
5. Launch `:NvimTreeToggle`
6. The number in the other window doesn't get updated
st1
_As you can see, there are only two windows but the right one shows number 3_

I tried to use some autocommand like `WinNew` or `WinClosed`, but they don't work...

**Comment by famiu** [comment]
> I can confirm this PR works well:
> 
>     * providers in inactive windows works well thanks to `winid` parameter
> 
>     * LSP hover doesn't make feline inactive in current window
> 
> 
> But NvimTree problem remains, and it's independent from `splitright` because in another scenario inactive windows aren't updated.
> To reproduce (no matter of `splitright` value):
> 
>     1. Open a buffer fullscreen
> 
>     2. Split vertically
> 
>     3. Launch `:NvimTreeToggle`
> 
>     4. Go to middle window
> 
>     5. Launch `:NvimTreeToggle`
> 
>     6. The number in the other window doesn't get updated
>        st1
>        _As you can see, there are only two windows but the right one shows number 3_
> 
> 
> I tried to use some autocommand like `WinNew` or `WinClosed`, but they don't work...

Can you try adding the `BufWinEnter` autocmd and see if it works

**Comment by ram02z** [comment]
>
> But NvimTree problem remains, and it's independent from `splitright` because in another scenario inactive windows aren't updated.
> To reproduce (no matter of `splitright` value):
> 
>     1. Open a buffer fullscreen
> 
>     2. Split vertically
> 
>     3. Launch `:NvimTreeToggle`
> 
>     4. Go to middle window
> 
>     5. Launch `:NvimTreeToggle`
> 
>     6. The number in the other window doesn't get updated
>        st1
>        _As you can see, there are only two windows but the right one shows number 3_
> 
> 
> I tried to use some autocommand like `WinNew` or `WinClosed`, but they don't work...

I can also reproduce this issue. However, I cannot reproduce if I skip the 4th step and also I cannot repoduce when using a plugin that also creates a left split, undotree, `UndoTreeToggle`.

**Comment by famiu** [comment]
> > But NvimTree problem remains, and it's independent from `splitright` because in another scenario inactive windows aren't updated.
> > To reproduce (no matter of `splitright` value):
> > ```
> > 1. Open a buffer fullscreen
> > 
> > 2. Split vertically
> > 
> > 3. Launch `:NvimTreeToggle`
> > 
> > 4. Go to middle window
> > 
> > 5. Launch `:NvimTreeToggle`
> > 
> > 6. The number in the other window doesn't get updated
> >    st1
> >    _As you can see, there are only two windows but the right one shows number 3_
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I tried to use some autocommand like `WinNew` or `WinClosed`, but they don't work...
> 
> I can also reproduce this issue. However, I cannot reproduce if I skip the 4th step and also I cannot repoduce when using a plugin that also creates a left split, undotree, `UndoTreeToggle`.

Can you try adding `BufWinEnter` autocmd and see if it works

**Comment by ram02z** [comment]
>
> Can you try adding `BufWinEnter` autocmd and see if it works

BufWinEnter doesn't work and also breaks lsp hover. WinLeave actually gets called at step 5 but the number still doesnt update.

**Comment by famiu** [comment]
> > Can you try adding `BufWinEnter` autocmd and see if it works
> 
> BufWinEnter doesn't work and also breaks lsp hover. WinLeave actually gets called at step 5 but the number still doesnt update.

At this point I'm thinking if it's an issue with the window number itself. Can you try switching to a different window and switching back to see if it gets fixed or if it still shows the wrong numbers

**Comment by ram02z** [comment]
> 
> At this point I'm thinking if it's an issue with the window number itself. Can you try switching to a different window and switching back to see if it gets fixed or if it still shows the wrong numbers

It is an issue with the window number. I took a look at how nvim-tree's handles window toggles and it uses `nvim_win_hide`, which makes sense why both `BufHidden` and `WinClosed` work. However, what I don't understand is why the window number isn't updated after the autocmd is triggered (`update_inactive_windows` definitely still gets called)

https://github.com/kyazdani42/nvim-tree.lua/blob/71122d798482e30c599d78aa7ae4a756c6e81a79/lua/nvim-tree/view.lua#L337

**Comment by famiu** [comment]
> > At this point I'm thinking if it's an issue with the window number itself. Can you try switching to a different window and switching back to see if it gets fixed or if it still shows the wrong numbers
> 
> It is an issue with the window number. I took a look at how nvim-tree's handles window toggles and it uses `nvim_win_hide`, which makes sense why both `BufHidden` and `WinClosed` work. However, what I don't understand is why the window number isn't updated after the autocmd is triggered (`update_inactive_windows` definitely still gets called)
> 
> https://github.com/kyazdani42/nvim-tree.lua/blob/71122d798482e30c599d78aa7ae4a756c6e81a79/lua/nvim-tree/view.lua#L337

Maybe it's because the window numbers don't actually change if the buffer is hidden.

**Comment by ram02z** [comment]
> 
> Maybe it's because the window numbers don't actually change if the buffer is hidden.

I mean I checked the window handle's number before and after step 5 and it does infact change from 3->2.

**Comment by famiu** [comment]
> > Maybe it's because the window numbers don't actually change if the buffer is hidden.
> 
> I mean I checked the window handle's number before and after step 5 and it does infact change from 3->2.

Then it's very strange for the window number to not be updated even after `update_inactive_windows` is called

**Comment by ram02z** [comment]
>
> Then it's very strange for the window number to not be updated even after `update_inactive_windows` is called. Either way I should probably add `BufHidden` as a trigger. Thoughts on that?

WinClosed seems more appropriate. It is very strange because if you add an autocmd like `CursorMoved` or `CursorHold` which update quite frequently, the window number does change to 2.

**Comment by famiu** [comment]
> > Then it's very strange for the window number to not be updated even after `update_inactive_windows` is called. Either way I should probably add `BufHidden` as a trigger. Thoughts on that?
> 
> WinClosed seems more appropriate. It is very strange because if you add an autocmd like `CursorMoved` or `CursorHold` which update quite frequently, the window number does change to 2.

I realized that no matter how many autocmds we add, some functionality is still inevitably going to break due to information not being updated. So at one point we have to decide what to add and what not to. That or we can go fully inefficient by integrating `update_all_windows` inside `generate_statusline`, which'd mean the statusline would get updated all the time. Again, it's a tradeoff.

**Comment by ram02z** [comment]
> 
> I realized that no matter how many autocmds we add, some functionality is still inevitably going to break due to information not being updated. So at one point we have to decide what to add and what not to. That or we can go fully inefficient by integrating `update_all_windows` inside `generate_statusline`, which'd mean the statusline would get updated all the time. Again, it's a tradeoff.

Yeah that is true. I think that the tradeoff is simply not worth it because I don't think most people want constant updates on their inactive windows(I know I don't). The current approach works fine but breaks with `nvim-tree` for some reason, I think that the issue should be tracked until an appropriate workaround/fix is found or you could leave this PR open. I don't think this will break any existing functionality though so maybe merging to master is best since we can get people to file bug reports if other plugins also have the same issue as `nvim-tree`.

**Comment by famiu** [comment]
> > I realized that no matter how many autocmds we add, some functionality is still inevitably going to break due to information not being updated. So at one point we have to decide what to add and what not to. That or we can go fully inefficient by integrating `update_all_windows` inside `generate_statusline`, which'd mean the statusline would get updated all the time. Again, it's a tradeoff.
> 
> Yeah that is true. I think that the tradeoff is simply not worth it because I don't think most people want constant updates on their inactive windows(I know I don't). The current approach works fine but breaks with `nvim-tree` for some reason, I think that the issue should be tracked until an appropriate workaround/fix is found or you could leave this PR open. I don't think this will break any existing functionality though so maybe merging to master is best since we can get people to file bug reports if other plugins also have the same issue as `nvim-tree`.
> 
> I do think `WinClosed` should be added since it is emitted whenever `nvim_win_hide` or `nvim_win_close` is called.

We could have a configuration option that makes the statusline update constantly, though I don't know if that's worth adding. But yes, I will add WinClosed. And I'm going to merge this PR once we decide if we should add an option to update the statusline continuously or not and take appropriate actions for that.

**Comment by ram02z** [comment]
> 
> We could have a configuration option that makes the statusline update constantly, though I don't know if that's worth adding. But yes, I will add `WinClosed`. And I'm going to merge this PR once we decide if we should add an option to update the statusline continuously or not and take appropriate actions for that. On another note, maybe allow users to configure the autocmds that trigger an inactive statusline update?

You know what, it might be better to leave it the end user to decide what additional autocmds they want to use. However, the current autocmds should stay as the default, and then only append autocmds that aren't default if a user specifies them. This approach does resonate with the design approach of feline.

**Comment by xeluxee** [comment]
Just discovered sth interesting, this issue could be linked to NvimTree itself

```
:autocmd WinClosed                                                                                                                                                            
--- Autocommands ---                                                                                                                                                          
WinClosed                                                                                                                                                                     
    *         lua require('core.nvimtree').on_close()                                                                                                                         
feline  WinClosed                                                                                                                                                             
    *         lua require("feline").update_inactive_windows()                                                                                                                 
NvimTree  WinClosed                                                                                                                                                           
    *         lua require'nvim-tree'.on_leave()                                                                                                                               
bufferline_update  WinClosed                                                                                                                                                  
    *         call bufferline#update_async()
```

Maybe `on_leave()` is causing a wrong behaviour...

**Comment by xeluxee** [comment]
Just implemented an update with debug method:

``` lua
function M.update_inactive_windows(debug)
    local current_win = api.nvim_get_current_win()

    for _, winid in ipairs(api.nvim_tabpage_list_wins(0)) do
        if debug == true then
            print(string.format("CHECKING window %d, while cur is %d", winid, current_win))
        end
        if api.nvim_win_get_config(winid).relative == '' and winid ~= current_win
        then
            if debug == true then
                print("-> Updated")
            end
            vim.wo[winid].statusline = require('feline').statusline(winid)
        end
    end

    -- Reset local statusline of current window to use the global statusline for it
    vim.wo.statusline = nil
end
```

I noticed that this function is called before NvimTree window is closed. Steps to reproduce:
1. Add this to autocommands in `init.lua`:
``` lua
        {
            'WinClosed',
            '*',
            'lua require("feline").update_inactive_windows(true)'
        },
```
2. `:set cmdheight=1` (so vim will stop to show messages)
3. restart and open NvimTree, then close it.
4. You'll see that messages are displayed before window is closed

This is why other windows don't get updated, because the first window (NvimTree) is still opened when `update_inactive_windows` is called.

**Comment by ram02z** [comment]
Nice find @xeluxee! I remember seeing someone use `timer_start()` to defer execution until all other autocommands are run. I think `vim.loop.new_timer()` is the appropriate equivalent. I have tested the below code and I cannot reproduce your issue anymore. Let me know if it breaks anything :D

```lua
-- Uses a timer with value 0 to defer executing the function until after
-- all other autocommands have run. This will ensure that inactive windows
-- are updated after any changes.
function M.update_inactive_windows()
    local timer = vim.loop.new_timer()
    timer:start(0, 0, vim.schedule_wrap(function()
        local current_win = api.nvim_get_current_win()

        for _, winid in ipairs(api.nvim_tabpage_list_wins(0)) do
            if api.nvim_win_get_config(winid).relative == '' and winid ~= current_win
            then
                vim.wo[winid].statusline = require('feline').statusline(winid)
            end
        end

        -- Reset local statusline of current window to use the global statusline for it
        vim.wo.statusline = nil
    end))
end
```

**Comment by famiu** [comment]
> UPDATE: seems like it breaks `vi_mode` on inactive windows. A quick reproduce is to invoke `:Telescope` and you should see Insert mode on all inactive windows (you need to have vi_mode on inactive windows). I don't think `vi_mode` should work on inactive windows anyway, so I guess it is fine?

That's the intended behavior though, right? `vi_mode` is the same for all windows since it's a global value independent of the window.

**Comment by ram02z** [comment]
> 
> That's the intended behavior though, right? `vi_mode` is the same for all windows since it's a global value independent of the window.

Yeah that is true, but I feel like `vim.defer_fn` may have other unwarranted side effects even though it solves the nvim-tree issue. I am honestly not sure how else we can ensure that `update_inactive_windows` is executed after other autocmds.

**Comment by famiu** [comment]
> > That's the intended behavior though, right? `vi_mode` is the same for all windows since it's a global value independent of the window.
> 
> Yeah that is true, but I feel like `vim.defer_fn` may have other unwarranted side effects even though it solves the nvim-tree issue. I am honestly not sure how else we can ensure that `update_inactive_windows` is executed after other autocmds.

I suppose this is still the best way we have. Another possibility I see is continuously updating inactive windows but in the background asynchronously. That being said, if we go with the current method, do you still think autocmd triggers for Feline updates should be user configurable?

**Comment by ram02z** [comment]
>
> I suppose this is still the best way we have. Another possibility I see is continuously updating inactive windows but in the background asynchronously. That being said, if we go with the current method, do you still think autocmd triggers for Feline updates should be user configurable?

I think asynchronous behaviour in neovim is hard to get right but if you do have a solution, I don't mind reviewing it. 

I don't think there is any harm in making autocmds user configurable, since if it breaks, it will be on the end user and their configuration. Having the option to extend the autocmds sounds nice.

**Comment by famiu** [comment]
> > I suppose this is still the best way we have. Another possibility I see is continuously updating inactive windows but in the background asynchronously. That being said, if we go with the current method, do you still think autocmd triggers for Feline updates should be user configurable?
> 
> I think asynchronous behaviour in neovim is hard to get right but if you do have a solution, I don't mind reviewing it.
> 
> I don't think there is any harm in making autocmds user configurable, since if it breaks, it will be on the end user and their configuration. Having the option to extend the autocmds sounds nice.

It was very simple to implement async. Just had to remove the autocmd triggers for update_inactive_windows and did this:
```lua
vim.loop.new_timer():start(0, vim.o.updatetime, vim.schedule_wrap(M.update_inactive_windows))
```

Ideally we could make the timer configurable too

**Comment by ram02z** [comment]
> 
> It was very simple to implement async. Just had to remove the autocmd triggers for update_inactive_windows and did this:
> ```lua
> vim.loop.new_timer():start(0, vim.o.updatetime, vim.schedule_wrap(M.update_inactive_windows))
> ```
> 
> Ideally we could make the timer configurable too

Oh that's what you mean, sorry I am tired, I was thinking of multithreading .If I recall correctly, leaving the timer handle open can cause memory leaks.

**Comment by famiu** [comment]
> > It was very simple to implement async. Just had to remove the autocmd triggers for update_inactive_windows and did this:
> > ```lua
> > vim.loop.new_timer():start(0, vim.o.updatetime, vim.schedule_wrap(M.update_inactive_windows))
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Ideally we could make the timer configurable too
> 
> Oh that's what you mean, sorry I am tired

It's fine

> I was thinking of multithreading

I guess I could give that a shot too

> If I recall correctly, leaving the timer handle open can cause memory leaks

And how would that be fixed?

**Comment by ram02z** [comment]
> 
> > I was thinking of multithreading
> 
> I guess I could give that a shot too

I am not even sure if it is possible because neovim runs on a single thread.

> 
> > If I recall correctly, leaving the timer handle open can cause memory leaks
> 
> And how would that be fixed?
> 

I think you have to close the handler once you are done with it, but thinking more about it, I'm not sure if you would need to do that for a statusline plugin.

**Comment by famiu** [comment]
> > > I was thinking of multithreading
> > 
> > 
> > I guess I could give that a shot too
> 
> I am not even sure if it is possible because neovim runs on a single thread.
> 

I mean, `vim.loop.new_thread` exists, so let me look into whether that can solve our problems or not.

> > > If I recall correctly, leaving the timer handle open can cause memory leaks
> > 
> > 
> > And how would that be fixed?
> 
> I think you have to close the handler once you are done with it, but thinking more about it, I'm not sure if you would need to do that for a statusline plugin.

Precisely. When are we "done with" the handler?

**Comment by ram02z** [comment]
I think the async code you posted is pretty much what the CursorHold autocmd already does. I think maybe just using `vim.schedule` instead of the one shot timer function, `vim.defer_fn`, would be more reliable, even though my testing had similar results.

**Comment by famiu** [comment]
> I think the async code you posted is pretty much what the CursorHold autocmd already does.

Except it does it asynchronously so it doesn't block Neovim.

> I think maybe just using `vim.schedule` instead of the one shot timer function, `vim.defer_fn`, would be more reliable, even though my testing had similar results.

It does seem more reliable

**Comment by famiu** [comment]
We could have the best of both worlds and asynchronously run `update_inactive_windows` everytime an autocmd trigger happens. But the simplest way to do that would be through plenary's async lib, and I don't know if that'd be worth adding an extra dependency.

**Comment by famiu** [comment]
So I've rebased this to the latest master and also added an `update_triggers` configuration option. This seems to be ready for merge now unless we go the async route

**Comment by famiu** [comment]
That being said, I think I'm going to merge this now, we've waited too long on this. If the merge causes any problems, please open a new issue.

**Comment by xeluxee** [comment]
I confirm this works really well!
Thanks @famiu @ram02z

**Pull request merged**
